
# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

# True color support (important for LazyVim)
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g status-position bottom
set -g status-interval 2
set -g status-style "bg=#1f2335,fg=#c0caf5"

set -g status-left "#[fg=#7aa2f7] #S "
set -g status-right "#[fg=#9ece6a] %Y-%m-%d %H:%M "

setw -g window-status-current-style "fg=#7aa2f7,bold"
setw -g window-status-style "fg=#565f89"

# Next / previous session with Alt+n / Alt+p
bind -n M-n next-window
bind -n M-p previous-window

set -sg escape-time 10

