# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

##### PREFIX #####
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

##### RELOAD #####
bind r source-file ~/.tmux.conf \; display "Reloaded!"

##### PANES #####
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

##### WINDOWS #####
bind c new-window -c "#{pane_current_path}"
bind -n M-n next-window
bind -n M-p previous-window
set -g detach-on-destroy off

##### MOUSE #####
set -g mouse on

##### VI MODE #####
setw -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

##### TRUE COLOR (FIXED) #####
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",tmux-256color:RGB"
set -as terminal-overrides ",xterm-256color:RGB"

##### ESCAPE SPEED #####
set -sg escape-time 10

##### HISTORY #####
set -g history-limit 50000

##### STATUS BAR (Rose Pine-ish transparent look) #####
set -g status-position bottom
set -g status-interval 2
set -g status-style "bg=default,fg=#e0def4"

set -g status-left "#[fg=#9ccfd8] #S "
set -g status-right "#[fg=#c4a7e7] %Y-%m-%d %H:%M "

setw -g window-status-current-style "fg=#9ccfd8,bold"
setw -g window-status-style "fg=#6e6a86"

##### PANE BORDERS #####
set -g pane-border-style "fg=#403d52"
set -g pane-active-border-style "fg=#9ccfd8"

##### CLIPBOARD SYNC #####
set -g set-clipboard on

##### PROJECTS #####
bind -n M-o display-popup -E -w 60% -h 70% "sesh picker"
bind -n M-i display-popup -E -w 60% -h 70% "lazygit"


##### SOURCE TPM #####
run '~/.tmux/plugins/tpm/tpm'
